name: C++ build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cpp-build:

    runs-on: ubuntu-latest

    steps:
    - name: Install DejaGNU
      run: sudo apt-get install dejagnu
    - uses: actions/checkout@v3
    - name: Initialize GNU build system
      run: |
        mkdir build
        autoreconf -f -i -s
    - name: Create build configuration
      working-directory: build
      run: ../configure
      env:
        CXX: g++-15
        CXXFLAGS: -std=c++23
    - name: Build
      run: make -C build
    - name: Tests
      run: make -C build check
    - name: Distribution
      run: make -C build dist
    - name: Distribution tests
      run: make -C build distcheck
      env:
        CXX: g++-15
        CXXFLAGS: -std=c++23
