name: C++ build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cpp-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install DejaGNU
      run: apt-get install dejagnu
    - name: Initialize GNU build system
      run: |
        autoreconf -f -i -s
        mkdir build
    - name: Create build configuration
      working-directory: build
      run: |
        ../configure
    - name: Build
      run: make -C build
    - name: Tests
      run: make -C build check
