name: C++ build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cpp-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Initialize GNU build system
      run: autoreconf -f -i -s
    - name: Create build configuration
      working-directory: build
      run: |
        ../configure
    - name: Build
      run: make
      working-directory: build
    - name: Tests
      run: make check
      working-directory: build
